version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn run build

artifacts:
  files:
    - '**/*'
  base-directory: build
